### ISSUE TITLE
@seorii\win32-displayconfig breaks during installation

### ISSUE THREAD

**Issue by tscpp** [Seo-Rii/electron-acrylic-window#68]
I have not had this problem before, so I tried to re-clone the repository; that did not work.

| yarn | npm | node | msbuild | windows |
| :-: | :-: | :-: | :-: | :-: |
| 1.22.11 | 6.14.13 | 14.17.1 | 2019 (16.11.2) |  21H1 |

```
yarn install v1.22.11
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
[4/5] Linking dependencies...
[5/5] Building fresh packages...
[1/5] ⠁ @seorii/win32-displayconfig
[5/5] ⠁ electron
[3/5] ⠁ core-js-pure
[-/5] ⠁ waiting...
error C:\Users\elias\Desktop\electron-acrylic-window\node_modules\@seorii\win32-displayconfig: Command failed.
Exit code: 1
Command: npm run rebuild
Arguments:
Directory: C:\Users\elias\Desktop\electron-acrylic-window\node_modules\@seorii\win32-displayconfig
Output:
> @seorii/win32-displayconfig@0.1.1 rebuild C:\Users\elias\Desktop\electron-acrylic-window\node_modules\@seorii\win32-displayconfig
> node-gyp rebuild


C:\Users\elias\Desktop\electron-acrylic-window\node_modules\@seorii\win32-displayconfig>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
Building the projects in this solution one at a time. To enable parallel build, please add the "-m" switch.
  win32-displayconfig.cc
  win_delay_load_hook.cc
C:\Users\elias\Desktop\electron-acrylic-window\node_modules\@seorii\win32-displayconfig\win32-displayconfig.cc(520,14): error C2065: 'DISPLAYCONFIG_OUTPUT_TECHNOLOGY_INDIRECT_VIRTUAL': undeclared identifier [C:\Users\elias\Desktop\electron-acrylic-window\node_modules\@seorii\win32-displayconfig\build\win32_displayconfig.vcxproj]
C:\Users\elias\Desktop\electron-acrylic-window\node_modules\@seorii\win32-displayconfig\win32-displayconfig.cc(520,1): error C2051: case expression not constant [C:\Users\elias\Desktop\electron-acrylic-window\node_modules\@seorii\win32-displayconfig\build\win32_displayconfig.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\MSBuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:375:28)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)
gyp ERR! System Windows_NT 10.0.19043
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\elias\Desktop\electron-acrylic-window\node_modules\@seorii\win32-displayconfig
gyp ERR! node -v v14.17.1
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @seorii/win32-displayconfig@0.1.1 rebuild: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @seorii/win32-displayconfig@0.1.1 rebuild script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

**Comment by Seo-Rii** [comment]
I can't reproduce the error.
Can you reinstall the window build tool and try again?

**Comment by tscpp** [comment]
The problem was that I had previously set the msbuild path to visual studio 2019 build tools.
